services:
  calculator:
    build: .
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: gunicorn -w 4 -b 0.0.0.0:5000 main:app
