name: Build and SAST with Bandit

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Compose (no cache)
        run: docker compose build --no-cache

      - name: Start app stack
        run: docker compose up -d

      - name: Wait for app to be ready
        run: |
          echo "Waiting for app..."
          sleep 10
          curl -sSf http://127.0.0.1:5000/health || echo "App health check failed"

      - name: Test calculator add API with curl
        run: |
          echo "Testing calculator API access..."
          curl -X GET "http://127.0.0.1:5000"
          echo "Testing addition for calculator API..."
          curl -X POST -H "Content-Type: application/json" -d '{"expression":"5+3"}' http://127.0.0.1:5000/calculate

      - name: Tear down Docker Compose stack and remove volumes
        run: docker compose down -v

  sast:
    runs-on: ubuntu-latest
    needs: build_and_deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build SAST Docker target with Bandit
        run: docker build --target sast -t my-app-sast .

      - name: Run Bandit container to display SAST results
        run: docker run --rm my-app-sast

      - name: Copy Bandit JSON report from container
        run: |
          docker run --rm -v ${{ github.workspace }}:/out my-app-sast cp /scan/bandit-report.json /out/

      - name: Upload Bandit JSON report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.json
