name: Build and SAST with Bandit

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Compose (no cache)
        run: docker compose build --no-cache

      - name: Start app stack
        run: docker compose up -d

  sast:
    runs-on: ubuntu-latest
    needs: build_and_deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build SAST Docker target with Bandit
        run: docker build --target sast -t my-app-sast .

      - name: Run Bandit container to display SAST results
        run: docker run --rm my-app-sast
